# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Wed Apr 22 01:14:24 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gvImage = MyGraphicsView(self.centralwidget)
        self.gvImage.setGeometry(QtCore.QRect(0, 0, 551, 551))
        self.gvImage.setDragMode(QtGui.QGraphicsView.ScrollHandDrag)
        self.gvImage.setObjectName("gvImage")
        self.tbSidebar = QtGui.QToolBox(self.centralwidget)
        self.tbSidebar.setGeometry(QtCore.QRect(557, 3, 241, 541))
        self.tbSidebar.setObjectName("tbSidebar")
        self.pageActions = QtGui.QWidget()
        self.pageActions.setGeometry(QtCore.QRect(0, 0, 241, 429))
        self.pageActions.setObjectName("pageActions")
        self.groupBox = QtGui.QGroupBox(self.pageActions)
        self.groupBox.setGeometry(QtCore.QRect(0, 210, 241, 211))
        self.groupBox.setObjectName("groupBox")
        self.plainTextEdit = QtGui.QPlainTextEdit(self.groupBox)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 30, 221, 171))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.tbSidebar.addItem(self.pageActions, "")
        self.pageSetup = QtGui.QWidget()
        self.pageSetup.setGeometry(QtCore.QRect(0, 0, 241, 429))
        self.pageSetup.setObjectName("pageSetup")
        self.groupBox_2 = QtGui.QGroupBox(self.pageSetup)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 221, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalSlider = QtGui.QSlider(self.groupBox_2)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 60, 160, 16))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QtGui.QSlider(self.groupBox_2)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(20, 120, 160, 16))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.spinBox = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox.setGeometry(QtCore.QRect(130, 30, 45, 23))
        self.spinBox.setObjectName("spinBox")
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 40, 53, 14))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 53, 14))
        self.label_2.setObjectName("label_2")
        self.spinBox_2 = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_2.setGeometry(QtCore.QRect(130, 90, 45, 23))
        self.spinBox_2.setObjectName("spinBox_2")
        self.tbSidebar.addItem(self.pageSetup, "")
        self.pageChunks = QtGui.QWidget()
        self.pageChunks.setGeometry(QtCore.QRect(0, 0, 241, 429))
        self.pageChunks.setObjectName("pageChunks")
        self.scrollArea = QtGui.QScrollArea(self.pageChunks)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 241, 421))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 239, 419))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.listView = QtGui.QListView(self.scrollAreaWidgetContents)
        self.listView.setGeometry(QtCore.QRect(0, 0, 241, 421))
        self.listView.setObjectName("listView")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tbSidebar.addItem(self.pageChunks, "")
        self.pageScanlines = QtGui.QWidget()
        self.pageScanlines.setGeometry(QtCore.QRect(0, 0, 241, 429))
        self.pageScanlines.setObjectName("pageScanlines")
        self.tbSidebar.addItem(self.pageScanlines, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExport)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tbSidebar.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "RrsmPng", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSidebar.setItemText(self.tbSidebar.indexOf(self.pageActions), QtGui.QApplication.translate("MainWindow", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSidebar.setItemText(self.tbSidebar.indexOf(self.pageSetup), QtGui.QApplication.translate("MainWindow", "Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSidebar.setItemText(self.tbSidebar.indexOf(self.pageChunks), QtGui.QApplication.translate("MainWindow", "Chunks", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSidebar.setItemText(self.tbSidebar.indexOf(self.pageScanlines), QtGui.QApplication.translate("MainWindow", "Scanlines", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport.setText(QtGui.QApplication.translate("MainWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))

from rrsmpng.MyGraphicsView import MyGraphicsView
