# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rrsmpng/MainWindow.ui'
#
# Created: Tue Aug 18 19:54:56 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1184, 815)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gvImage = MyGraphicsView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gvImage.sizePolicy().hasHeightForWidth())
        self.gvImage.setSizePolicy(sizePolicy)
        self.gvImage.setDragMode(QtGui.QGraphicsView.ScrollHandDrag)
        self.gvImage.setObjectName("gvImage")
        self.horizontalLayout.addWidget(self.gvImage)
        self.tbSidebar = QtGui.QToolBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbSidebar.sizePolicy().hasHeightForWidth())
        self.tbSidebar.setSizePolicy(sizePolicy)
        self.tbSidebar.setMinimumSize(QtCore.QSize(300, 0))
        self.tbSidebar.setMaximumSize(QtCore.QSize(0, 16777215))
        self.tbSidebar.setObjectName("tbSidebar")
        self.pageActions = QtGui.QWidget()
        self.pageActions.setGeometry(QtCore.QRect(0, 0, 300, 634))
        self.pageActions.setObjectName("pageActions")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pageActions)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_3 = QtGui.QGroupBox(self.pageActions)
        self.groupBox_3.setObjectName("groupBox_3")
        self.rbParsing1 = QtGui.QRadioButton(self.groupBox_3)
        self.rbParsing1.setGeometry(QtCore.QRect(30, 50, 151, 20))
        self.rbParsing1.setObjectName("rbParsing1")
        self.rbParsing2 = QtGui.QRadioButton(self.groupBox_3)
        self.rbParsing2.setGeometry(QtCore.QRect(30, 80, 141, 20))
        self.rbParsing2.setObjectName("rbParsing2")
        self.rbParsing3 = QtGui.QRadioButton(self.groupBox_3)
        self.rbParsing3.setGeometry(QtCore.QRect(30, 110, 141, 20))
        self.rbParsing3.setObjectName("rbParsing3")
        self.rbParsing4 = QtGui.QRadioButton(self.groupBox_3)
        self.rbParsing4.setGeometry(QtCore.QRect(30, 140, 161, 20))
        self.rbParsing4.setObjectName("rbParsing4")
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox = QtGui.QGroupBox(self.pageActions)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pteLog = QtGui.QPlainTextEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pteLog.sizePolicy().hasHeightForWidth())
        self.pteLog.setSizePolicy(sizePolicy)
        self.pteLog.setReadOnly(True)
        self.pteLog.setPlainText("")
        self.pteLog.setObjectName("pteLog")
        self.verticalLayout.addWidget(self.pteLog)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.tbSidebar.addItem(self.pageActions, "")
        self.pageSetup = QtGui.QWidget()
        self.pageSetup.setGeometry(QtCore.QRect(0, 0, 300, 634))
        self.pageSetup.setObjectName("pageSetup")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.pageSetup)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_2 = QtGui.QGroupBox(self.pageSetup)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.sbWidth = QtGui.QSpinBox(self.groupBox_2)
        self.sbWidth.setObjectName("sbWidth")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.sbWidth)
        self.hsWidth = QtGui.QSlider(self.groupBox_2)
        self.hsWidth.setOrientation(QtCore.Qt.Horizontal)
        self.hsWidth.setObjectName("hsWidth")
        self.formLayout.setWidget(1, QtGui.QFormLayout.SpanningRole, self.hsWidth)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_2)
        self.sbHeight = QtGui.QSpinBox(self.groupBox_2)
        self.sbHeight.setObjectName("sbHeight")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.sbHeight)
        self.hsHeight = QtGui.QSlider(self.groupBox_2)
        self.hsHeight.setOrientation(QtCore.Qt.Horizontal)
        self.hsHeight.setObjectName("hsHeight")
        self.formLayout.setWidget(10, QtGui.QFormLayout.SpanningRole, self.hsHeight)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.tbSidebar.addItem(self.pageSetup, "")
        self.pageChunks = QtGui.QWidget()
        self.pageChunks.setGeometry(QtCore.QRect(0, 0, 300, 634))
        self.pageChunks.setObjectName("pageChunks")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.pageChunks)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtGui.QScrollArea(self.pageChunks)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 278, 612))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lvChunks = QtGui.QListView(self.scrollAreaWidgetContents)
        self.lvChunks.setObjectName("lvChunks")
        self.verticalLayout_3.addWidget(self.lvChunks)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.tbSidebar.addItem(self.pageChunks, "")
        self.pageScanlines = QtGui.QWidget()
        self.pageScanlines.setGeometry(QtCore.QRect(0, 0, 300, 634))
        self.pageScanlines.setObjectName("pageScanlines")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.pageScanlines)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtGui.QLabel(self.pageScanlines)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.label_4 = QtGui.QLabel(self.pageScanlines)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_3 = QtGui.QLabel(self.pageScanlines)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.vsScanlineScroll = QtGui.QSlider(self.pageScanlines)
        self.vsScanlineScroll.setOrientation(QtCore.Qt.Vertical)
        self.vsScanlineScroll.setObjectName("vsScanlineScroll")
        self.gridLayout.addWidget(self.vsScanlineScroll, 1, 2, 1, 1)
        self.vsScanlineZoom = QtGui.QSlider(self.pageScanlines)
        self.vsScanlineZoom.setOrientation(QtCore.Qt.Vertical)
        self.vsScanlineZoom.setObjectName("vsScanlineZoom")
        self.gridLayout.addWidget(self.vsScanlineZoom, 1, 0, 1, 1)
        self.pntScanlines = MyPainterScanline(self.pageScanlines)
        self.pntScanlines.setObjectName("pntScanlines")
        self.gridLayout.addWidget(self.pntScanlines, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.cbRtupdate = QtGui.QCheckBox(self.pageScanlines)
        self.cbRtupdate.setObjectName("cbRtupdate")
        self.verticalLayout_6.addWidget(self.cbRtupdate)
        self.tbSidebar.addItem(self.pageScanlines, "")
        self.horizontalLayout.addWidget(self.tbSidebar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1184, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExport)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tbSidebar.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "RrsmPng", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Parsing", None, QtGui.QApplication.UnicodeUTF8))
        self.rbParsing1.setText(QtGui.QApplication.translate("MainWindow", "Standard PIL loading", None, QtGui.QApplication.UnicodeUTF8))
        self.rbParsing2.setText(QtGui.QApplication.translate("MainWindow", "Safe loading", None, QtGui.QApplication.UnicodeUTF8))
        self.rbParsing3.setText(QtGui.QApplication.translate("MainWindow", "Seek chunk in file", None, QtGui.QApplication.UnicodeUTF8))
        self.rbParsing4.setText(QtGui.QApplication.translate("MainWindow", "Read as a chunk blob", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSidebar.setItemText(self.tbSidebar.indexOf(self.pageActions), QtGui.QApplication.translate("MainWindow", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSidebar.setItemText(self.tbSidebar.indexOf(self.pageSetup), QtGui.QApplication.translate("MainWindow", "Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSidebar.setItemText(self.tbSidebar.indexOf(self.pageChunks), QtGui.QApplication.translate("MainWindow", "Chunks", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Scanlines", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Scroll", None, QtGui.QApplication.UnicodeUTF8))
        self.cbRtupdate.setText(QtGui.QApplication.translate("MainWindow", "Realtime update", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSidebar.setItemText(self.tbSidebar.indexOf(self.pageScanlines), QtGui.QApplication.translate("MainWindow", "Scanlines", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport.setText(QtGui.QApplication.translate("MainWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))

from rrsmpng.MyPainterScanline import MyPainterScanline
from rrsmpng.MyGraphicsView import MyGraphicsView
